#!/bin/sh

set -e

PIQIVSN="$1"

# do nothing if $PIQI set
if [ ! -n "$PIQI" ] && [ -n "$PIQIVSN" ]
then
    mkdir -p priv
    (
        cd priv ;
        wget -O - \
            https://github.com/alavrik/piqi-binary/archive/v${PIQIVSN}.tar.gz \
                | tar zxvf -
        mv "piqi-binary-${PIQIVSN}" piqi-binary
    )
fi
