#!/bin/sh

set -e

PIQIBINREPO="$1"
PIQIVSN="$2"

# do nothing if $PIQI set
if [ ! -n "$PIQI" ] && [ -n "$PIQIVSN" ]
then
    mkdir -p priv
    (
        cd priv ;
        wget -q -O - \
            https://github.com/${PIQIBINREPO}/archive/v${PIQIVSN}.tar.gz \
                | tar zxvf -
        mv "piqi-binary-${PIQIVSN}" piqi-binary
    )
fi
