#!/bin/sh

set -e

# do nothing if $PIQI set
if [ ! -n "$PIQI" ] && [ -n "$PIQIVSN" ]
then
    mkdir -p deps
    (
        cd deps ;
        wget -O - \
            https://github.com/alavrik/piqi-binary/archive/v${PIQIVSN}.tar.gz \
                | tar zxvf -
        mv "piqi-binary-v${PIQIVSN}" piqi-binary
    )
fi
